### ISSUE TITLE
clang-format-10 broken?

### ISSUE THREAD

**Issue by steven-johnson** [DoozyX/clang-format-lint-action#13]
It looks like clangFormatVersion=10 is supposed to be supported, but when I try using it, it fails, e.g.:

https://github.com/halide/Halide/pull/5122/checks?check_run_id=874907072

Is this fully supported yet?

**Comment by DoozyX** [comment]
Sorry. I haven't released the version jet, will test it today and it should work, you will need to update the action version after it.

**Comment by DoozyX** [comment]
@steven-johnson try updating to v0.7, it should work now

**Comment by MarvinKlemp** [comment]
@DoozyX I had the same issue, upgrading to v0.7 fixed it for me.
