### ISSUE TITLE
Use fixed clang-format version

### ISSUE THREAD

**Issue by Flamefire** [DoozyX/clang-format-lint-action#2]
It would be better to use a fixed clang-format version as formatting style changes between versions and the config might not even be compatible.

Maybe make the version a parameter?

**Comment by DoozyX** [comment]
Yes, the parameter option whould be nice, I was thinking about that before. Will check in the weekend when I have some free time if that is possible.

**Comment by DoozyX** [comment]
The parameters to the actions are currently only accessible at runtime and not at build time of docker container, so if we want to choose the version, we should download/build the clang-format in the script which will remove the purpose of docker. Another option is to have the version of this action correspond to the clang-format version ex clang-format-lint v9 = clang-format v9 etc, but it would make maintaining worse?
There is an issue to add build args to actions that should easily fix this issue.
https://github.community/t5/GitHub-Actions/Feature-Request-Build-args-support-in-Docker-container-actions/m-p/37815#M3086

**Comment by Flamefire** [comment]
Other idea: There are static builds of clang-format that don't require runtime libs. They'll probably "just work" on Github actions (or in a minimal docker to be OS-independent). Maybe include 5-9?

I agree that abusing the version for the clang-format version is not a good idea. Better is something like "v1" has 9, "v2" has 5-9, v3 has 5-10 and so on as they are released.

I don't know enough about GH actions, but maybe you can even include the binaries in the repo and don't require building a docker

**Comment by DoozyX** [comment]
Added in v0,5
Could you check it?
