### ISSUE TITLE
Please support CLI options to clang-format

### ISSUE THREAD

**Issue by wyessen** [DoozyX/clang-format-lint-action#3]
I want to be able to specify command line options to clang-format. For instance, it may be beneficial to support the `--style` option to specify the style (would be awesome if `--style=file` with the specified format file was supported).

**Comment by DoozyX** [comment]
The file option is there by default, but if you want to use some other style I will look into adding this.

**Comment by wyessen** [comment]
@DoozyX Yep, that's right. Thanks! I think it may still be nice to be able to specify one of the presets (LLVM, Google, Chromium, Mozilla, or WebKit).

**Comment by gabrieldemarmiesse** [comment]
I made a PR for that: #5
