### ISSUE TITLE
Support for ClangFormat 16 and 17

### ISSUE THREAD

**Issue by marcelwa** [DoozyX/clang-format-lint-action#53]
Thank you for providing this action! It has been really helpful for my projects.

I was wondering if you could add support for ClangFormat versions 16 and 17 soon. It would really help to keep formatting straight across local installations and the action.

Many thanks!

**Comment by Ballen7** [comment]
I do not think there is a version 17 released yet.

**Comment by marcelwa** [comment]
Many thanks for getting at this so quickly!

It's of course totally possible that I misinterpreted [the respective documentation](https://clang.llvm.org/docs/ClangFormat.html) and that version 17 is only a pre-release. I apologize for the confusion in that case.
