### ISSUE TITLE
Excluding multiple directories

### ISSUE THREAD

**Issue by nicovanduijn** [DoozyX/clang-format-lint-action#6]
I cannot figure out the proper syntax to define more than one directory to be excluded.

I've tried things like
```
exclude: './extern,./build'
exclude: './extern ./build'
exclude: './{extern,build}'
exclude: '{./extern,./build}'
```

An example on the readme would be really helpful

**Comment by DeveloperPaul123** [comment]
I've used the following and it seems to work:

```
exclude: './libs,./utilities'
```

Basically just a comma separated list.

**Comment by nicovanduijn** [comment]
That was the first thing I tried, but it doesn't work for me:
![image](https://user-images.githubusercontent.com/14265408/76786342-5ae73780-67b7-11ea-9a55-c3fb0c9b1483.png)

**Comment by DeveloperPaul123** [comment]
Ok after looking at the [source](https://github.com/DoozyX/clang-format-lint-action/blob/master/run-clang-format.py#L43) I found something that works. In the root of your project, you can add a `.clang-format-ignore` file and add the directories you want to ignore. Each directory you want to ignore should be a new line on the file.

The parser in the github action also supports comments and glob patterns.

Example:
```
# third-party libraries
./libs
./external 

./cmake

# ignore all unit test files
./*/tests
./*/*/tests
./*/*/*/tests

# ignore all test applications
./*/testapps
./*/*/testapps
./*/*/*/testapps
```

**Comment by DoozyX** [comment]
Multiple arguments with the same name are not possible by GitHub actions and I don't think comma-separated values are a good idea. As @DeveloperPaul123 mentioned there is .clang-format-ignore file that you can pass multiple exclude patterns. Added information about it in README. @nicovanduijn does this solve the issue?

**Comment by nicovanduijn** [comment]
Yeah, that workaround is fine by me

**Comment by eguiraud** [comment]
Hi, the README says that it's possible to pass multiple directories to `exclude`, but this issue seems to imply the opposite?

Quoting the README under `exclude`:

> Example: './third_party' or 'third_party exclude' for multiple
