### ISSUE TITLE
Add Support for Clang Format 18

### ISSUE THREAD

**Issue by DeveloperPaul123** [DoozyX/clang-format-lint-action#68]
With LLVM releasing 18.x, would be good to add support for this version in this Github action. 

Thanks!

**Comment by echoix** [comment]
Seems to be blocked by https://github.com/muttleyxd/clang-tools-static-binaries/issues/39, while the repo has merged the PR to make that build, it has not made the release draft published afterwards

**Comment by echoix** [comment]
The upstream repo created a release, so this is now unblocked!

**Comment by echoix** [comment]
Did you already start a PR for it?

**Comment by DeveloperPaul123** [comment]
I have not started a PR.

**Comment by Demonslay335** [comment]
Bump?
