### ISSUE TITLE
Where can I specify the .clang-format file?

### ISSUE THREAD

**Issue by mohabouje** [DoozyX/clang-format-lint-action#7]
I've seen in the docs that by default the formatter uses the repository .clang-format file as default style. I have this file in the root of the repository but somehow the outputs I see do not match with the formatting that I get by running it locally:

```
/usr/bin/docker run --name doozyclangformatlint05_992745 --label 430c1a --workdir /github/workspace --rm -e INPUT_SOURCE -e INPUT_EXTENSIONS -e INPUT_CLANGFORMATVERSION -e INPUT_EXCLUDE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/smart-engine/smart-engine":"/github/workspace" doozy/clang-format-lint:0.5  "." "none" "c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx" "9"
```

As you can see, this is the configuration I'm using:

** engine/smart-engine":"/github/workspace" doozy/clang-format-lint:0.5  "." "none" "c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx" "9" **

Locally, I'm running: clang-format version 9.0.0 (tags/google/stable/2019-05-14)

What am I doing wrong?

**Comment by mohabouje** [comment]
Not sure if it's the main issue but it fixes the problem. It's missing the -style=file argument in the command line that is executed:

```
    invocation = [args.clang_format_executable, "-style=file", file]
```

**Comment by morphogencc** [comment]
Is it possible to add a `.clang-format` file anywhere besides in the root?  I'm placing them in `.github/linters` because I'm using Github's Super-Linter, and it'd be great if I could point both to the same config file easily.
