### ISSUE TITLE
Distutils has been removed from Python 3.12

### ISSUE THREAD

**Issue by BotellaA** [DoozyX/clang-format-lint-action#73]
Starting with Python 3.12, Distutils has been removed https://peps.python.org/pep-0632/
It looks like the docker image python:3-alpine is based on 3.12, so this action no longer works.

Could you upgrade the Python script, or as a quick workaround use the python:3.11-alpine image?

Thanks

**Comment by levtoji** [comment]
@DoozyX Can you please enable PRs? It seems it should be very easy to fix.
https://stackoverflow.com/questions/77941994/what-is-setuptools-alternative-to-the-deprecated-distutils-strtobool

**Comment by DoozyX** [comment]
@levtoji PRs are always enabled, let me know if there is any issue

**Comment by levtoji** [comment]
Yeah sorry about the ping, I forgot about how to create PRs for not owned repos.

**Comment by GeckoEidechse** [comment]
#75

**Comment by eguiraud-pf** [comment]
Hi, thanks for the quick action! It might also be a good idea to fix the full Python version backing the action to avoid similar problems in the future

**Comment by GeckoEidechse** [comment]
Given that #75 didn't work out and the current "fix" is to just pin the Python version to 3.11, this should probably be re-openend ^^"

**Comment by morningman** [comment]
Hi, is there any further action for this issue?

**Comment by Vallishp** [comment]
@DoozyX  can you please review this solution?

https://github.com/DoozyX/clang-format-lint-action/pull/78

**Comment by DoozyX** [comment]
Can you still reproduce it and if so on what version?
