### ISSUE TITLE
distutil package issue

### ISSUE THREAD

**Issue by panyogesh** [DoozyX/clang-format-lint-action#79]
While running  

  File "/run-clang-format.py", line 25, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'

**Comment by echoix** [comment]
There's missing a bit of information to your bug report, but I assume you aren't using the latest released version of this action. This was addressed in at least 0.18.2.

**Comment by panyogesh** [comment]
I will test on latest and update. We used "9ea72631b74e61ce337d0839a90e76180e997283" which is around 3 years old. I realized that

**Comment by bogdan-rosianu** [comment]
I can confirm that updating the workflow to 0.18.2 fixes the issue 👍

**Comment by panyogesh** [comment]
Thanks for the response. Closing the ticket as its working on latest version.
