### ISSUE TITLE
Disable header file reordering 

### ISSUE THREAD

**Issue by panyogesh** [DoozyX/clang-format-lint-action#80]
Is it possible to disable header file reordering.
The intent is clear but effects the existing projects

**Comment by panyogesh** [comment]
I tried with ---style "{SortIncludes: false}" and seems to be working as expected. If there any suggestions let me know.
We can close the ticket.

**Comment by kellijohnson-NOAA** [comment]
Thank you @panyogesh for this issue thread, it helped me navigate a similar desire that I had though I am using a yml file to run the action so I wasn't sure how to proceed with your suggestion when I also wanted to indicate other information in the style argument. I found that I could do something like the following in the .yml file to run the action and everything worked as planned.
```
style: "{BasedOnStyle: Google, SortIncludes: false}"
```
Thanks again! And, I am just commenting in case more people come to this issue seeking a little bit more context.
